version: '2'

volumes:
  twofishesvolume: {}

services:
  twofishes:
    image: zmyle/twofishes:latest
    volumes:
      - twofishesvolume:/opt/twofishes
    ports:
      - '8080:8080'
      - '8081:8081'
      - '8082:8082'
      - '8083:8083'
    restart: always
